### ISSUE TITLE
Error when loading with antigen

### ISSUE THREAD

**Issue by bdougherty** [gparker42/zsh-dirnav#3]
I'm using antigen to install this (`antigen bundle gparker42/zsh-dirnav dirnav`) and it works great except for this error that happens when my shell first opens:

```
.antigen/bundles/gparker42/zsh-dirnav/dirnav:unfunction:143: no such hash table element: dirnav
```

I've manually commented that line out for now, but is there any way to update it so the `unfunction` call only happens if `dirnav` is defined?

**Comment by gparker42** [comment]
Brad, can you try this test in place of the original `unfunction`?
```
if [ ${+functions[dirnav]} -eq 1 ]; then
    unfunction dirnav;
fi
```

**Comment by bdougherty** [comment]
@gparker42 that works perfectly

**Comment by gparker42** [comment]
Fixed. Thanks!
